#!/usr/bin/env python3
"""Regenerate crates/disktree-core/UPSTREAM_DIGESTS.txt from an upstream
disktree checkout (see crates/disktree-core/VENDORED.md for the pin and the
update procedure). Usage:

    scripts/vendor-digests.py <path-to-disktree-checkout>/crates/disktree-core
"""
import hashlib
import sys
from pathlib import Path

HEADER = """# Per-file SHA-256 of the vendored disktree-core copy, as read from the
# upstream checkout at revision {rev}.
# Generated by scripts/vendor-digests.py; the pinned_upstream test fails
# if the vendored copy drifts from these digests.
"""


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    source = Path(sys.argv[1])
    if not (source / "src").is_dir():
        print(f"not a disktree-core checkout: {source}")
        return 1
    revision = sys.argv[3] if len(sys.argv) > 3 else "158f9cc2f0b332194a3ffc5acec47760c99146d8"
    lines = [HEADER.format(rev=revision).rstrip("\n")]
    for path in sorted(source.rglob("*.rs")):
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        lines.append(f"{digest}  {path.relative_to(source)}")
    target = Path(__file__).resolve().parent.parent / "crates" / "disktree-core" / "UPSTREAM_DIGESTS.txt"
    target.write_text("\n".join(lines) + "\n")
    print(f"wrote {target} ({len(lines) - 1} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
